#!/usr/bin/env python3
"""Emit manifest.json — the curated 60 (20 per direction), ranked, with docs.
Text condensed faithfully from each studio's notes-*.md; order == rank."""
import json, pathlib
HERE = pathlib.Path(__file__).resolve().parent

# (direction, id, subdir, title, motif, register, wordmark, concept, why, risk, wide)
D = [
# ================= Direction A — Julia-Native (ranked) =================
("A","a3pulse-03","A_julia_native","Heart of Three","heart / three-dot","minimalist","icon-only",
 "A thin heart outline is threaded through the three Julia dots — purple & green at the lobes, red at the point — so the heart is drawn *by* the triad, not beside it.",
 "A whole heart emerges from just three dots and a hairline stroke: minimum ink, maximum recognition.",
 "Departs from the canonical one-up/two-down arrangement; the cut heart can shrink at 32px.",False),
("A","a1rhythm-01","A_julia_native","Rhythm Strip Classic","ECG / three-dot","scientific","icon-only",
 "Three P-QRS-T complexes on a running ECG baseline; each R-peak tip is capped by a Julia dot, so the dots literally *are* the heartbeats.",
 "The most literal fusion of 'Julia dots' and 'heartbeat' — reads both ways instantly.",
 "Closest to a generic ECG logo; differentiation rests on the exact dot placement.",False),
("A","a2return-06","A_julia_native","Pulse Orbit","ECG / attractor / three-dot","scientific","icon-only",
 "A limit-cycle ring doubles as a heartbeat: its lower arc between the red and green dots interrupts into a small QRS spike.",
 "Single most literal fusion of HRV (the spike) and phase-space (the ring) — reads as both at once.",
 "The QRS spike is small relative to the ring and softens first at 32px.",False),
("A","a3pulse-07","A_julia_native","Groove","ECG / negative-space / three-dot","minimalist","icon-only",
 "Three dots fused into a row with a full PQRST zigzag channel cut straight through them as bright negative space.",
 "Strongest, most scientifically honest ECG read in the lane while staying pure negative space.",
 "Row layout departs furthest from the canonical triangle; colors carry the identity.",False),
("A","a1rhythm-05","A_julia_native","IBI Comb","IBI tick-marks / three-dot","scientific","icon-only",
 "A row of vertical ticks with deliberately irregular spacing (an RR-interval comb); three thicker ticks are dot-capped.",
 "Irregular tick spacing is honest shorthand for 'variability' — the core HRV concept, with near-zero clutter.",
 "Thin gray filler ticks can recede at tiny sizes, leaving 3 dots-on-sticks.",False),
("A","a2return-01","A_julia_native","Limit-Cycle Ring","attractor / three-dot","minimalist","icon-only",
 "A thin closed orbit threads through the three dots as if they were bodies riding a stable limit cycle; an arrowhead marks travel.",
 "One continuous stroke reads instantly as 'orbit', and the triad sits exactly where the Julia mark expects it.",
 "The directional arrowhead is subtle and may vanish at 16px.",False),
("A","a2return-07","A_julia_native","Return Map Minimal","Poincaré / three-dot","scientific","icon-only",
 "A minimal Poincaré return map: axes, a dashed identity diagonal, a lean SD1/SD2 cloud, and three dots stretched along the diagonal.",
 "The most scientifically honest Poincaré plot in the lane while still reading as three Julia dots.",
 "Diagonal arrangement can parse as 'just a scatter plot' to someone who doesn't know the Julia mark.",False),
("A","a1rhythm-02","A_julia_native","Interval Calipers","IBI-gap / three-dot","scientific","icon-only",
 "Three beats as beads on a rhythm line; unequal double-arrow brackets beneath measure the gaps — HRV as literally unequal intervals.",
 "Directly visualizes the package's core measurement (the ⟷ interval), which nothing else does as explicitly.",
 "The caliper arrows are the smallest detail and soften first under downscaling.",False),
("A","a3pulse-04","A_julia_native","Heart Cut","heart / negative-space / three-dot","minimalist","icon-only",
 "The canonical tightly-overlapping triad with a small heart masked out of the negative space exactly where the three dots meet.",
 "First read is 'three Julia dots'; second read reveals the hidden heart — a rewarding easter egg.",
 "At 32px the tiny heart cutout can shrink to a faint highlight.",False),
("A","a2return-02","A_julia_native","Poincaré Diagonal","Poincaré / three-dot","scientific","icon-only",
 "The upright Julia triangle sits inside a faint 45° ellipse cloud with axes and an identity diagonal behind it.",
 "Keeps the Julia triangle 100% intact while layering in genuine HRV semantics as background texture.",
 "At favicon size the axes/diagonal disappear, leaving just the triangle.",False),
("A","a3pulse-02","A_julia_native","Sinus Spark","pulse / three-dot","minimalist","icon-only",
 "Pulse rings radiate from the purple dot alone, casting it as the pacemaker (sinus node) that fires first.",
 "The asymmetric energy source gives a clear focal point and a distinct silhouette from other ring marks.",
 "The pacemaker nuance may read simply as 'one big dot, two small' without context.",False),
("A","a1rhythm-09","A_julia_native","Monitor Grid","ECG / clinical monitor / three-dot","illustrative","icon-only",
 "A bedside-monitor bezel with a faint graph-paper grid behind an ECG trace whose three R-peaks are the Julia dots.",
 "The rounded bezel + grid instantly signals 'clinical monitor', adding context the plain strip lacks.",
 "Most detail-dense mark; the grid fades to nothing at 32px — best used above favicon size.",False),
("A","a2return-08","A_julia_native","Concentric Orbit","pulse / attractor / three-dot","minimalist","icon-only",
 "Pulse rings ripple outward from a shared center; the triad rides the outermost ring — orbit and beat-propagation at once.",
 "Concentric rings are extremely robust at small sizes and the triad sits confidently on top.",
 "The inner rings are decorative and could be dropped without hurting the concept.",False),
("A","a2return-04","A_julia_native","Trail Triad","attractor / three-dot","illustrative","icon-only",
 "Each dot trails a short comet-tail arc, all curling the same way, implying synchronized orbital motion.",
 "Motion trails are an intuitive, low-cognitive-load way to say 'orbit' — the most dynamic mark in the lane.",
 "Pale trails can read as smudges/shadows at very small sizes.",False),
("A","a1rhythm-04","A_julia_native","Pulse Ring","pulse / limit-cycle / three-dot","minimalist","icon-only",
 "The rhythm strip bent into a closed loop (a recurring cardiac cycle) with clock-like ticks and the triad marking beats on the rim.",
 "Only circular composition in the lane, nodding to the limit-cycle dynamics vocabulary.",
 "Weakest at reading 'heartbeat' first glance — leans toward 'Julia mark in a circle'.",False),
("A","a2return-05","A_julia_native","Spiral Converge","attractor / spiral / three-dot","scientific","icon-only",
 "A spiral trajectory winds outward from center and settles onto the top purple dot — a phase-space path converging onto a limit cycle.",
 "Directly illustrates the 'converging to a limit cycle' dynamics idea, distinct from the pure-ring marks.",
 "The delicate inner windings blur first below ~24px; the triad stays legible regardless.",False),
("A","a3pulse-05","A_julia_native","R-Spike","ECG / R-peak / three-dot","minimalist","icon-only",
 "The purple dot grows a narrow triangular spike off its crown, turning the dot itself into the silhouette of an ECG R-peak.",
 "One dot doing double duty as both 'Julia purple' and 'R-peak' — about as reductive as the idea can get.",
 "At small sizes the spike could soften into a flame/teardrop rather than an explicit ECG reference.",False),
("A","a1rhythm-07","A_julia_native","Breath Wave","pulse (RSA) / three-dot","illustrative","icon-only",
 "A slow sinusoid (respiratory sinus arrhythmia — breathing's modulation of heart rate) carries three beats at crest, midline, trough.",
 "The only soft/organic register in the lane, giving range while staying grounded in real RSA physiology.",
 "A smooth wave alone can read 'signal/audio' more than 'heart' without the dot colors anchoring it.",False),
("A","a1rhythm-03","A_julia_native","Tachogram Steps","tachogram / three-dot","scientific","icon-only",
 "A beat-to-beat interval series (tachogram) drawn as a jagged polyline; three of five vertices are the colored Julia dots, two are neutral anchors.",
 "The zigzag height literally encodes IBI variability — exactly what a tachogram is.",
 "Could be mistaken for a generic line-chart icon without HRV context.",False),
("A","a3pulse-08","A_julia_native","Ring Rhythm","pulse / three-dot","minimalist","icon-only",
 "The three dots are open rings with a small Julia-blue pulse line threading the gaps between them like a beat passing through.",
 "Outline dots + a wired pulse line is a genuinely different figure-ground treatment from every filled mark.",
 "Thin ring strokes and the blue squiggle are the most detail-dense; least margin for shrinking.",False),
# ================= Direction B — HRV-First (ranked) =================
("B","b3heart-02","B_hrv_first","Loop Beat Heart","heart (looping line)","minimalist","icon-only",
 "The heart outline drawn as one continuous open stroke — purple left arc, green right — meeting at a red dot at the point.",
 "Huge negative space reads immediately as a heart while feeling like a signal trace, not clip-art.",
 "Relies on the viewer completing the shape from an open contour.",False),
("B","b2phase-01","B_hrv_first","Poincaré Cloud","Poincaré / attractor","scientific","icon-only",
 "The honest Poincaré plot — NN(n) vs NN(n+1) samples scattered inside an elongated ellipse on the 45° identity line.",
 "Instantly reads as 'Poincaré plot' to any HRV researcher — the field's single most iconic chart.",
 "At favicon size the scatter can read as a generic dotted blob.",False),
("B","b1ecg-05","B_hrv_first","R-Peak Bolt","ECG / R-peak","minimalist","icon-only",
 "The QRS complex reduced to its single essential gesture — a bold Q-R-S zigzag, purple→blue gradient, no P/T waves.",
 "The most abstracted, favicon-proof mark: thick, few points, unmistakable spike silhouette.",
 "Without P/T context some may read a generic 'lightning bolt'; leans on the blue accent more than most.",False),
("B","b1ecg-03","B_hrv_first","Pulse Tile","ECG (container)","app-icon","icon-only",
 "A rounded-square app-icon tile in Julia purple with a bold white ECG trace knocked through the center.",
 "Extremely legible at favicon size; the tile form factor is exactly what app icons are judged against.",
 "Single-color tile is the least 'Julia-coded' on its own; relies on family context.",False),
("B","b2phase-04","B_hrv_first","Lorenz Wings","attractor / Lorenz butterfly","minimalist","icon-only",
 "The two-lobe topology of the Lorenz attractor stylized as one continuous infinity stroke crossing at the saddle point.",
 "Captures the defining 'two wings, one crossing' structure in a single elegant stroke.",
 "Could read as a plain infinity symbol to viewers unfamiliar with the attractor.",False),
("B","b3heart-01","B_hrv_first","Cleft Beat Heart","heart / ECG-spike","minimalist","icon-only",
 "A two-tone geometric heart (purple/green) whose natural top cleft bursts into a small red QRS zigzag.",
 "The spike literally grows from the heart's own anatomy, so the beat is structural, not decorative.",
 "At very small sizes the thin spike can soften into a short tick.",False),
("B","b2phase-08","B_hrv_first","Nested Cycles","attractor / nested limit cycles","scientific","icon-only",
 "Two concentric orbits at very different scale — a big loose loop (green, high HRV) against a small tight loop (red, low HRV).",
 "The size contrast alone tells the HRV story (bigger orbit = more variability) with no text.",
 "Could be misread as a plain target/bullseye without the HRV framing.",False),
("B","b1ecg-08","B_hrv_first","Pulse Emitter","ECG + pulse (radiating)","scientific","icon-only",
 "A compact red R-peak spike broadcasting three concentric rhythm waves outward in purple, green, and blue.",
 "Reads as signal + transmission — exactly what HRV feature extraction is — distinct from every 'line in a box'.",
 "Off-center; at a glance could be mistaken for a wifi/signal icon if the red spike doesn't register first.",False),
("B","b3heart-08","B_hrv_first","Faceted Heart","abstract geometric heart","minimalist","icon-only",
 "A low-poly heart built from three flat color facets (purple, green, red) meeting at a shared center.",
 "Sharp facet lines and flat blocking feel deliberately engineered/scientific rather than decorative.",
 "Can momentarily read as a shield or gem before 'heart' resolves.",False),
("B","b2phase-03","B_hrv_first","Limit Cycle","attractor / limit cycle","minimalist","icon-only",
 "A Van der Pol relaxation-oscillator limit cycle drawn as a bold stadium-shaped orbit with a beat riding the trajectory.",
 "A closed loop is the simplest, boldest way to say 'dynamical system in equilibrium' — clear even at 32px.",
 "A stadium shape alone could be mistaken for a rounded-rectangle icon.",False),
("B","b2phase-02","B_hrv_first","SD Compass","Poincaré / SD1-SD2 axes","minimalist","icon-only",
 "SD1 (short axis) and SD2 (long axis) — the two numbers every Poincaré analysis reports — abstracted into a caliper cross on the diagonal with a ghost ellipse and mean-NN dot.",
 "Turns two abstract HRV metrics into an immediately legible crosshair mark, distinct from every ellipse-based logo.",
 "Without HRV context it can read as 'a green X', missing the SD1/SD2 reference.",False),
("B","b3heart-03","B_hrv_first","Sonar Pulse","pulse rings","minimalist","icon-only",
 "A beat propagating outward as thick concentric rings (purple→blue→green) tightening toward a solid red core.",
 "Pure radial symmetry and bold ring widths make it the most instantly 'pulse' and it holds perfectly at favicon size.",
 "Without a literal heart/ECG shape it reads 'pulse/signal' more than 'heart'.",False),
("B","b1ecg-02","B_hrv_first","Capsule Monitor","ECG (container)","app-icon","icon-only",
 "A two-tone purple/green capsule tile with a bold white rhythm trace running through it.",
 "The capsule silhouette is memorable while the white-on-color trace reads instantly as 'heart monitor'.",
 "The pill shape could read as 'medicine' without the trace doing the identifying work.",False),
("B","b2phase-06","B_hrv_first","Return-Map Heart","heart / return-map scatter","illustrative","icon-only",
 "A return-map scatter deliberately arranged so the point cloud's silhouette reads as a heart.",
 "Delivers a heart 'constructed from dots' while staying in the data/attractor vocabulary — a knowing wink.",
 "Least scientifically literal mark here; a purist could object no real return map looks like a heart.",False),
("B","b1ecg-01","B_hrv_first","QRS Line","ECG","minimalist","icon-only",
 "The honest P-QRS-T complex as a single confident stroke — no container, no ornament, Julia purple.",
 "The single most literal 'this is an ECG' read in the set; survives any size or background.",
 "Single-color mark leans least on the Julia palette; could read as a generic health icon.",False),
("B","b3heart-05","B_hrv_first","IBI Caliper","IBI-gap","scientific","icon-only",
 "Two R-peak spikes on a baseline with a double-headed arrow measuring the gap between them, like a dimension line.",
 "This is literally what the package measures — nothing needs explaining to an HRV-literate viewer.",
 "The dashed guide lines are the thinnest elements; first to soften on print.",False),
("B","b1ecg-04","B_hrv_first","Tri-Lead Stack","ECG (multi-lead)","scientific","icon-only",
 "Three stacked rhythm-strip leads, one in each core Julia color, gesturing at multi-lead recording.",
 "Reads as genuine biomedical-signal vocabulary while still delivering the 'three Julia colors' cue.",
 "At extreme miniaturization the three thin lanes have the least margin before merging.",False),
("B","b2phase-09","B_hrv_first","Pulse Ellipses","Poincaré / pulse rings","minimalist","icon-only",
 "A heartbeat rippling outward along the Poincaré diagonal — three same-orientation ellipses of increasing size, decreasing opacity.",
 "Merges 'pulse' and 'Poincaré diagonal' into one ripple mark, distinct from scatter or cross variants.",
 "The fainter outer rings can wash out at favicon size or on busy backgrounds.",False),
("B","b1ecg-06","B_hrv_first","Rhythm Ring","ECG / pulse loop","geometric","icon-only",
 "A continuous monitoring loop of four quarter-arcs (one per Julia color) broken at the top by a single red R-peak spike.",
 "Uses all four palette colors at once without a three-dot cliché; the segmented ring says 'continuous monitoring'.",
 "At small sizes reads more as a segmented-loader icon; the spike is the only cardiac cue.",False),
("B","b2phase-10","B_hrv_first","Triangular Orbit","attractor / limit cycle","minimalist","icon-only",
 "One continuous asymmetric closed trajectory (a limit cycle) that visits three phase-space nodes in Julia's three colors.",
 "Satisfies the three-color convention while staying unmistakably 'orbit', not 'logo triangle'.",
 "The closest B mark to Julia's own three-dot logo; needs the loop bold so it doesn't collapse to three dots.",False),
# ================= Direction C — Hybrid / Fusion (ranked) =================
("C","c2lobe-08","C_hybrid","Dot-Fused Heart","heart / three-dot (dots as lobes)","minimalist","icon-only",
 "Two big Julia dots (purple, green) sit exactly where a heart's lobes belong, fused, with red filling the point beneath.",
 "The cleanest fusion in the project — reads as heart AND as two Julia dots simultaneously.",
 "Very low risk; mainly keep the ink outline crisp so the red sliver isn't lost when small.",False),
("C","c1trace-09","C_hybrid","Heart from a Heartbeat","heart glyph / ECG / three-dot","illustrative","icon-only",
 "An abstract heart built entirely from a single bent ECG line (no valentine curves); lobes and dip marked by the three dots.",
 "Satisfies 'heart glyph built from curves not cliché' directly, and is the most universally legible C mark.",
 "Closest to a generic heart-outline icon if the dots were ever removed or miscolored.",False),
("C","c2lobe-01","C_hybrid","Tri-Slice Heart","heart / three wedges","minimalist","icon-only",
 "A solid heart cut into three Mercedes-style 120° wedges from its centroid — the triad *is* the heart, sliced.",
 "Instant heart read; the straight radial cuts feel intentional/geometric and stay crisp at any size.",
 "Hard straight seams are less 'organic'; can scan as pie art before heart for some.",False),
("C","c2lobe-06","C_hybrid","Negative Heart","heart (negative space) / three-dot","minimalist","icon-only",
 "Three large solid Julia circles fuse into a clover badge with a heart punched out of the middle as negative space.",
 "The cleverest negative-space use in the set — the heart is implied yet an outline keeps it instantly legible.",
 "Fast scanners may parse 'three overlapping circles' before the heart-shaped hole.",False),
("C","c3word-04","C_hybrid","H♥L","heart / Poincaré-cloud / monogram","typographic","includes text",
 "Bold 'H' and 'L' flank a geometric heart standing in for the middle of the name; a tiny dot cluster inside nods to a Poincaré cloud.",
 "Strongest square wordmark — clean, bold, reads as letters+heart even at 32px; the I♥NY substitution is instantly parseable.",
 "The internal dot cloud is a bonus detail invisible below ~64px.",False),
("C","c1trace-02","C_hybrid","Poincaré Triad","Poincaré / three-dot","scientific","icon-only",
 "A tilted Poincaré ellipse cloud along the 45° identity line whose three densest clusters are the three Julia dots.",
 "Honors the real SD1/SD2 ellipse geometry while making the dominant read exactly the Julia triad.",
 "Faint scatter dots vanish at 32px, leaving '3 dots in an ellipse'.",False),
("C","c1trace-03","C_hybrid","Tachogram Triad","IBI-gap / tachogram / three-dot","scientific","icon-only",
 "Three IBI bars of different heights rise from a baseline, each capped by a Julia dot, linked by a thin trend line.",
 "Bar-chart language reads instantly as 'time-series data', grounding the triad in recognizable HRV output.",
 "Could be mistaken for a generic bar-chart icon if the colors were muted.",False),
("C","c2lobe-04","C_hybrid","Three-Stroke Heart","heart / negative-space","illustrative","icon-only",
 "The heart drawn only as an outline, stitched from three thick rounded brush-stroke arcs in the three Julia colors.",
 "Confident negative space; a very legible line-art heart that still telegraphs 'three Julia colors'.",
 "The two short top arcs could weaken at extreme small sizes if stroked too thin.",False),
("C","c3word-05","C_hybrid","Triad Pulse Lockup","three-dot / ECG underline","typographic","includes text",
 "The Julia three-dot triangle on an ECG baseline with a peak beneath, paired with the full 'HeartRateLab' wordmark.",
 "The safest, most legible default lockup — Julia package + heartbeat + full name at a glance.",
 "The least novel of the lockups; closest in spirit to the reference seed.",True),
("C","c2lobe-03","C_hybrid","Trefoil Pulse","pulse / three-dot (petals)","minimalist","icon-only",
 "Three dot-derived teardrop petals meet at a small blue pulse-core, rotated 120° apart — a three-fold beat.",
 "A clean, original silhouette unmistakably built from three equal colored parts meeting at one beating point.",
 "Reads as pulse/trefoil more than a literal heart — the weakest 'heart' read of its studio.",False),
("C","c1trace-07","C_hybrid","Pulse Ring","pulse / ECG / three-dot","scientific","icon-only",
 "A thin heart-monitor ring (ECG wrapped into a circle) with three radial pulse-blips 120° apart, each ending in a Julia dot.",
 "Perfect rotational symmetry and a monitor-ring frame make 'pulse' unmistakable while the triad stays intact.",
 "The small radial ticks can fuse into the dots at 32px, reducing to 'ring + 3 dots'.",False),
("C","c2lobe-09","C_hybrid","Radiating Pulse Heart","heart / pulse (heart-shaped rings)","scientific","icon-only",
 "Three nested heart contours scaling down to a solid red core, rippling outward like a pulse — rings reshaped as hearts.",
 "An original combination of two brief motifs (pulse rings + heart) that reads neither generic nor cliché.",
 "The outer purple ring is the thinnest element; needs contrast at favicon size.",False),
("C","c1trace-04","C_hybrid","Limit-Cycle Knot","attractor / limit cycle / three-dot","illustrative","icon-only",
 "An asymmetric organic closed loop (a Van der Pol relaxation-oscillation limit cycle, not a circle) with the three dots riding the trajectory at uneven points.",
 "The lopsided non-circular contour reads distinctly as a dynamical-systems trajectory while still resolving into the triad.",
 "Without dynamics-literate context some viewers may just see 'a blob'.",False),
("C","c3word-07","C_hybrid","R-Peak Letter Lockup","limit-cycle / R-peak-as-letter","typographic","includes text",
 "A Van der Pol limit-cycle icon; in the wordmark the 'R' of 'Rate' is crowned by a sharp ECG spike on its cap.",
 "Doubles Julia-native (blue accent, closed-loop dynamics) and HRV (R-peak) in one detail without hurting legibility.",
 "The crowned 'R' reads best at ≥200px wide; at tiny sizes it looks like an accent mark.",True),
("C","c2lobe-05","C_hybrid","Orbiting Beat","heart / three-dot (orbital)","illustrative","icon-only",
 "A small solid ink heart at center while the three Julia dots orbit it on a thin ring, like electrons around a nucleus.",
 "A distinct atomic/orbital framing used nowhere else; the heart core stays legible even if the ring vanishes.",
 "The orbit ring and dots are the smallest elements; can lose contrast under 32px.",False),
("C","c1trace-10","C_hybrid","Spiral Attractor","attractor / spiral / three-dot","scientific","icon-only",
 "A true logarithmic phase-space spiral (a damped oscillator converging on a fixed point) with three passes marked by the three dots at decreasing radius.",
 "Matches the brief's spiral vocabulary; the converging composition reads as 'settling into rhythm'.",
 "The multi-turn curve has the most path complexity; must stay thick-stroked to avoid muddiness when small.",False),
("C","c2lobe-02","C_hybrid","Venn Pulse Heart","heart / three-dot (Venn circles)","scientific","icon-only",
 "Three translucent Julia-triad circles overlap inside a heart clip; their alpha-blended intersections nod to statistical Venn diagrams while the clip guarantees a heart.",
 "The overlap/blend is a subtle wink at the package's statistical heritage, with a guaranteed heart silhouette.",
 "At very small sizes the blended overlaps can read a touch muddy.",False),
("C","c3word-01","C_hybrid","Tri-Chrome HRL","three-dot (via color) / ECG underline","typographic","includes text",
 "The initials H-R-L each set in one Julia color, underlined by a thick ECG line with a single R-peak spike under the 'R'.",
 "Reads instantly as an acronym mark and a heartbeat trace at once; strong at large and favicon scale.",
 "Three letter colors could feel busy on a busy background; wants a neutral backdrop.",False),
("C","c2lobe-07","C_hybrid","Petal Heart","heart / three-dot (petals)","illustrative","icon-only",
 "Three dot-derived teardrop petals — purple and green lobes, red point — overlap so their union reads as one continuous heart.",
 "A softer, more organic heart than the wedge/Venn versions, still obviously built from three colored parts.",
 "The red petal is mostly hidden, showing only as a thin sliver — the third color can be missed at a glance.",False),
("C","c3word-08","C_hybrid","Heart Badge Lockup","heart / ECG-underlining-word","typographic","includes text",
 "A two-tone geometric heart paired with 'HeartRateLab' riding a continuous ECG baseline that bumps into an R-peak under 'Rate'.",
 "The most approachable lockup — the heart reads instantly and the underline ties the ECG motif to the name itself.",
 "Leans most on the 'heart' cliché; kept honest by the bicolor split and ECG baseline.",True),
]

def main():
    out = []
    seen = {"A":0,"B":0,"C":0}
    for direction, id_, sub, title, motif, register, wm, concept, why, risk, wide in D:
        seen[direction]+=1
        out.append({
            "id": id_, "direction": direction, "file": f"{sub}/{id_}.svg",
            "title": title, "motif": motif, "register": register, "wordmark": wm,
            "concept": concept, "why": why, "risk": risk,
            "rank": seen[direction], "wide": wide,
        })
    (HERE/"manifest.json").write_text(json.dumps(out, indent=2, ensure_ascii=False))
    print("manifest.json:", {k:v for k,v in seen.items()}, "total", len(out))

if __name__ == "__main__":
    main()
