#!/usr/bin/env python3
"""Build the HRV feature Pokédex inventory.

Parses every ``@register function`` block in ``src/Features.jl`` for its docstring
metadata (domains, aliases, one-line definition, declared Distribution family),
drops the 11 internal ``Representation: true`` helpers, and merges the fitted
normative priors from ``docs/normative_priors.csv``.

Emits three artifacts consumed downstream:
  * docs/zoo_gen/inventory.jl     -- Julia data file `include`d by make_entry.jl
  * docs/src/zoo/_inventory.json  -- machine-readable inventory
  * docs/src/zoo/_inventory.md    -- human Documenter table (Pokédex index)

Run from the repo root:  python3 docs/zoo_gen/gen_inventory.py
"""
import re, json, csv, os
from collections import Counter

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
FEATURES = os.path.join(REPO, "src", "Features.jl")
PRIORS   = os.path.join(REPO, "docs", "normative_priors.csv")
WINDOWED = os.path.join(REPO, "test", "testdata", "nsr2db", "windowed_w360_s120_features.csv")
ZOO      = os.path.join(REPO, "docs", "src", "zoo")
GENDIR   = os.path.join(REPO, "docs", "zoo_gen")


def parse_features():
    lines = open(FEATURES).read().split("\n")
    n = len(lines)
    idx = [i for i, l in enumerate(lines) if l.strip().startswith("@register function")]
    idx.append(n)
    feats, order = {}, []
    for k in range(len(idx) - 1):
        start, end = idx[k], idx[k + 1]
        block = "\n".join(lines[start:end])
        name = re.search(r"@register\s+function\s+(\w+)\s*\(", lines[start]).group(1)
        dom = re.search(r"Domains:\s*(.*)", block)
        dist = re.search(r"Distribution:\s*(\w+)", block)
        rep = re.search(r"Representation:\s*(\w+)", block)
        alias = re.search(r"Aliases:\s*(.*)", block)
        ds = re.search(r'"""(.*?)"""', block, re.S)
        defline = ""
        if ds:
            dl = [l.strip() for l in ds.group(1).split("\n") if l.strip()]
            if len(dl) > 1:
                defline = dl[1]
        feats[name] = dict(
            name=name,
            domains=[d.strip() for d in (dom.group(1) if dom else "").split(",") if d.strip()],
            dist=dist.group(1).strip() if dist else "",
            representation=("true" in rep.group(1).lower()) if rep else False,
            aliases=[a.strip() for a in (alias.group(1) if alias else "").split(",") if a.strip()],
            docdef=defline,
        )
        order.append(name)
    return feats, order


def load_priors():
    p = {}
    with open(PRIORS) as f:
        for row in csv.DictReader(f):
            p[row["feature"]] = row
    return p


def build():
    feats, order = parse_features()
    prior = load_priors()
    wset = set(open(WINDOWED).readline().strip().split(","))
    inv = []
    for name in order:
        f = feats[name]
        if f["representation"]:
            continue
        p = prior.get(name, {})
        inv.append(dict(
            name=name, aliases=f["aliases"], domains=f["domains"],
            primary_domain=f["domains"][0] if f["domains"] else "nonlinear",
            family=f["dist"], definition=(p.get("definition") or f["docdef"]),
            equation=p.get("equation", ""), prior_family=p.get("family", ""),
            prior_call=p.get("prior_call", ""),
            param1_name=p.get("param1_name", ""), param1_value=p.get("param1_value", ""),
            param2_name=p.get("param2_name", ""), param2_value=p.get("param2_value", ""),
            n_valid=p.get("n_valid", ""), ks_pvalue=p.get("ks_pvalue", ""),
            prior_status=p.get("status", "not in CSV") if p else "not in CSV",
            in_windowed_csv=(name in wset),
            window_size=p.get("window_size", "360"), stride=p.get("stride", "120"),
        ))
    return inv


def num(x):
    try:
        v = float(x)
        return "NaN" if v != v else repr(v)
    except Exception:
        return "NaN"


def jstr(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def jvec(xs):
    return "[" + ", ".join(jstr(x) for x in xs) + "]"


def write_julia(inv):
    out = [
        "# AUTO-GENERATED by docs/zoo_gen/gen_inventory.py -- do not edit by hand.",
        "# HRV feature inventory: docstring metadata (src/Features.jl) merged with",
        "# fitted normative priors (docs/normative_priors.csv). 53 user-facing features.",
        "const INVENTORY = [",
    ]
    for x in inv:
        out.append(
            "    (name=" + jstr(x["name"])
            + ", primary_domain=" + jstr(x["primary_domain"])
            + ", domains=" + jvec(x["domains"])
            + ", aliases=" + jvec(x["aliases"])
            + ", family=" + jstr(x["family"])
            + ", definition=" + jstr(x["definition"])
            + ", equation=" + jstr(x["equation"])
            + ", prior_family=" + jstr(x["prior_family"])
            + ", param1_name=" + jstr(x["param1_name"]) + ", param1_value=" + num(x["param1_value"])
            + ", param2_name=" + jstr(x["param2_name"]) + ", param2_value=" + num(x["param2_value"])
            + ", n_valid=" + (str(int(x["n_valid"])) if str(x["n_valid"]).isdigit() else "0")
            + ", ks_pvalue=" + num(x["ks_pvalue"])
            + ", prior_status=" + jstr(x["prior_status"])
            + ", in_windowed_csv=" + ("true" if x["in_windowed_csv"] else "false")
            + ", window_size=" + str(x["window_size"] or 360)
            + ", stride=" + str(x["stride"] or 120) + "),"
        )
    out += ["]", "const INVENTORY_BY_NAME = Dict(x.name => x for x in INVENTORY)"]
    open(os.path.join(GENDIR, "inventory.jl"), "w").write("\n".join(out) + "\n")


def write_md(inv):
    c = Counter(x["primary_domain"] for x in inv)
    md = [
        "# HRV Feature Inventory (Pokédex index)", "",
        '!!! note "Auto-generated"',
        "    This table is generated from `src/Features.jl` docstrings merged with the fitted",
        "    normative priors in `docs/normative_priors.csv`. Do not edit by hand -- regenerate",
        "    with `docs/zoo_gen/gen_inventory.py`.", "",
        "**53 user-facing features** (64 `@register function` declarations minus 11 internal "
        "representations, e.g. `diff`/`pgram`/`px`/`histogram`/`dfa`).",
        f"Domain split: **{c['time']} time**, **{c['frequency']} frequency**, "
        f"**{c['geometric']} geometric**, **{c['nonlinear']} nonlinear**.",
        "**36** features have a fitted normative prior *and* a column in the NSR2DB windowed",
        "feature table (`test/testdata/nsr2db/windowed_w360_s120_features.csv`); the remaining",
        "**17** (HR spread, ULF, all entropies, DFA-alpha2) are declared but were not windowed/fitted.",
        "",
        "| Feature | Domain | Dist. family | Fitted prior | Normal-plot data? | Definition |",
        "|---------|--------|--------------|--------------|-------------------|------------|",
    ]
    for x in inv:
        prior = x["prior_call"] if x["prior_status"] == "ok" else "-- (not fitted)"
        hasplot = "yes (nsr2db)" if x["in_windowed_csv"] else "no column"
        al = ", ".join("`%s`" % a for a in x["aliases"][:3]) if x["aliases"] else ""
        name = "`%s`" % x["name"] + (" <br><sub>%s</sub>" % al if al else "")
        md.append(f"| {name} | {x['primary_domain']} | {x['family']} | {prior} | {hasplot} | {x['definition']} |")
    md += ["", "See [`rmssd`](rmssd.md) for the reference dex entry."]
    open(os.path.join(ZOO, "_inventory.md"), "w").write("\n".join(md) + "\n")


if __name__ == "__main__":
    os.makedirs(ZOO, exist_ok=True)
    os.makedirs(GENDIR, exist_ok=True)
    inv = build()
    json.dump(inv, open(os.path.join(ZOO, "_inventory.json"), "w"), indent=1)
    write_julia(inv)
    write_md(inv)
    print(f"wrote inventory.jl, _inventory.json, _inventory.md ({len(inv)} features)")
