#!/usr/bin/env python3
"""Emit series2/manifest2.json — 30 IBI-first designs, grouped & ranked, with the
orchestrator's top-3 flagged. Text condensed from the three notes-*.md files."""
import json, pathlib
HERE = pathlib.Path(__file__).resolve().parent  # docs/logos/series2

# group, id, subdir, title, motif, register, wordmark, concept, why, risk, rank, top3, top3_reason
D = [
# -------- IBI-Comb icons --------
("icons","comb-01","ibi_icons","Rhythm Comb","tick comb / event raster","scientific","icon-only",
 "Base A intensified — 12 ticks clustered in irregular groups so the rhythm itself, not just three gaps, reads as variable; the three tallest ticks carry the Julia dots.",
 "The most literal refinement of the hero motif you chose; scales density up without losing the baseline-and-ticks read.",
 "Busiest of the set; at 32px the filler ticks fuzz into a grey band (the three dots still pop).",1,3,
 "It's the direct, stronger evolution of the exact mark you already picked (Base A) — the standalone 'symbol' of the system. Crop it for social/app icons; drop to comb-08 for a true 16–32px favicon."),
("icons","comb-04","ibi_icons","Cycle Ring","comb bent into a full ring","minimalist","icon-only",
 "The comb bent into a full ring — ticks radiate from a circle at irregular angular gaps (a cyclic cardiac cycle); three extended ticks carry the Julia dots.",
 "The most distinctive silhouette in the set (radial vs linear) and reads well as an app icon at any size.",
 "Could look clock-like; mitigated by irregular (non-12-hour) spacing and the dot colors.",2,None,None),
("icons","comb-08","ibi_icons","Minimal Gaps","ultra-minimal beats + gap marks","minimalist","icon-only",
 "Stripped to three large Julia dots on a barely-there baseline with two small caliper marks making the unequal gaps explicit — the comb fully implied.",
 "Cleanest of the set and the best true favicon: nothing is lost in downscaling (verified crisp at 32px).",
 "Loses the comb texture that makes Base A distinctive; reads generic if the caliper marks are removed.",3,None,None),
("icons","comb-06","ibi_icons","Tachogram","tachogram (point series + line)","scientific","icon-only",
 "Classic tachogram — beat number on x, interval duration as point height on y, points joined by a step line; three enlarged colored points anchor identity among grey ones.",
 "The most 'real HRV analysis output' of the set — anyone who's plotted NN-intervals recognizes it instantly.",
 "The zig-zag could brush 'ECG' if too spiky; kept rounded and modest (whitelisted IBI vocabulary).",4,None,None),
("icons","comb-02","ibi_icons","Interval Calipers","interval brackets / calipers","scientific","icon-only",
 "Three beat-dots on the baseline; two engineering-style dimension brackets span beat1→2 and beat2→3 at different lengths, explicitly measuring the unequal IBI gaps.",
 "The most explicit 'this measures a duration' read — good where the measurement idea must be instant.",
 "Could be mistaken for a bar-chart/table icon if colors are stripped.",5,None,None),
("icons","comb-09","ibi_icons","Floating Beats","event markers over a plain raster","minimalist","icon-only",
 "A regular tick timeline underneath with three Julia dots floating above at irregular heights, each linked by a thin dashed stem — the floating heights are the variability signal.",
 "Cleanly separates 'when' (regular raster) from 'how variable' (floating heights) — a distinct two-layer composition.",
 "Dashed stems can vanish at 32px (the floating dots still read as the hero).",6,None,None),
("icons","comb-07","ibi_icons","Poincaré","Poincaré plot","scientific","icon-only",
 "NN(n) vs NN(n+1) scatter — axes, a 45° diagonal, grey interval-pairs inside a faint SD1/SD2 ellipse on the diagonal, with three colored anchor points.",
 "Signals analytical depth (a real HRV metric plot) and is visually the most distinctive 'documentation' companion mark.",
 "Most detail-heavy icon; axis lines and scatter thin out at 32px — bump size if used very small.",7,None,None),
("icons","comb-03","ibi_icons","Cardiac Arc","comb bent into an arc","minimalist","icon-only",
 "The comb bent along a gentle upward arc — one cycle read left-to-right along a curve; ticks radiate outward and three carry the Julia dots.",
 "Softens the motif (less 'ruler', more 'pulse') and reads well as a badge/favicon silhouette.",
 "Faint resemblance to a crown/rainbow at a glance; dot colors and tick texture disambiguate.",8,None,None),
("icons","comb-10","ibi_icons","Interval Barcode","barcode of intervals","minimalist","icon-only",
 "Only vertical bars packed edge to edge — bar width encodes IBI duration; most are grey, three are purple/red/green standing in for the identity beats.",
 "The boldest, most brandable icon; reads as a 'waveform of durations' rather than any ECG shape.",
 "Deliberately has no circular dots — identity is carried by bar color, not dots (flag if reviewers expect circles).",9,None,None),
("icons","comb-05","ibi_icons","Vertical Raster","vertical comb / stacked raster","scientific","icon-only",
 "The comb rotated 90° — a vertical baseline with horizontal ticks stacked at irregular vertical spacing; three ticks extend to the Julia dots.",
 "A useful alternate orientation for sidebar/vertical-nav icon slots.",
 "Less immediately 'cardiac' than the horizontal version; the raster read needs the dots to anchor it.",10,None,None),
# -------- Triad + name lockups --------
("lockups","lock-04","lockups","Underlined by the Comb","IBI comb as underline / type","typographic","includes text",
 "No separate icon block — the whole 'HeartRateLab' wordmark is underlined by an irregular IBI tick comb; three ticks in the Julia colors are dot-capped, echoing identity inline with the type.",
 "The strongest type-led option; the comb underline scans as a data-signature rather than decoration.",
 "At small sizes the underline ticks can merge into a solid rule — best at medium+ (favicon should fall back to an icon-only mark).",1,1,
 "My overall favorite. It fuses both things you liked — the IBI comb and the name lockup — into one mark: the package name literally written onto an inter-beat recording. Distinctive, legible, and unmistakably about interval variability."),
("lockups","lock-02","lockups","Tick-Comb Mini","IBI tick-comb (dot-capped)","typographic","includes text",
 "Three colored ticks at unequal spacing and heights (= unequal IBI durations), each capped with a small Julia dot — a compact, icon-first version of Base A's comb, set left of the wordmark.",
 "Ties directly to the hero comb while staying a clean 'icon + name' lockup — the format you said you liked.",
 "At very small sizes the dot caps can fuse with the ticks; keep dot radius ≥ stroke width.",2,2,
 "The horizontal 'logo next to the name' you specifically liked — but rebuilt honestly: a tiny IBI comb instead of the ECG spike. This is the everyday workhorse lockup for README headers and docs."),
("lockups","lock-03","lockups","Measured Gap","beat dots + interval caliper","typographic","includes text",
 "Three dot-beats on a timeline plus a small caliper explicitly measuring the interval between the last two beats — the 'we measure intervals' story made literal, beside the wordmark.",
 "The caliper is unambiguous — nobody could mistake this for a heartbeat monitor.",
 "The caliper is small at icon scale; needs thicker strokes below ~64px stand-alone.",3,None,None),
("lockups","lock-01","lockups","Triad on the Timeline","beat-event dots on a timeline","typographic","includes text",
 "The three Julia dots sit directly on a plain baseline with visibly unequal gaps — the gaps are the inter-beat intervals, no waveform involved — beside the wordmark.",
 "The most legible/neutral option; reads instantly as 'events on a line' — a safe default lockup.",
 "Low risk; can look generic if not seen alongside the tick-comb variants.",4,None,None),
("lockups","lock-05","lockups","Comb Stack","IBI tick-comb (stacked)","typographic","includes text",
 "Stacked lockup — Base A's full tick-comb icon (grey ticks + three dot-capped colored ticks) centered above the wordmark.",
 "The most faithful port of the Base A hero icon into a lockup — best if you want one lockup that matches the standalone icon exactly.",
 "None major; verify icon/word vertical rhythm at target sizes.",5,None,None),
("lockups","lock-08","lockups","Heart·Rate·Lab","mini comb + weighted wordmark","typographic","includes text",
 "'Rate' is set larger and in Julia red for emphasis (the product's core subject), paired with a tiny 3-tick dot-capped comb at left.",
 "The weighted 'Rate' is a memorable reading aid tying the accent color to the product's central concept.",
 "Three text runs must stay baseline-aligned if re-flowed/localized; keep as one composed unit.",6,None,None),
("lockups","lock-06","lockups","Triad Stack (Tight)","beat-event dots on a timeline","typographic","includes text",
 "Stacked lockup — triad on a plain timeline (larger dots, unequal gaps) above a tightly tracked wordmark.",
 "Big dots read well even at small stacked-icon crops; tight tracking gives a modern condensed feel.",
 "Tight tracking pushes legibility slightly; don't set textLength smaller.",7,None,None),
("lockups","lock-09","lockups","Big Icon, Wide Track","beat dots + interval caliper","typographic","includes text",
 "A larger triad-on-timeline icon with a caliper under the last gap, paired with a looser-tracked wordmark on a slightly raised baseline — a scale/alignment study.",
 "Shows the lockup scaling gracefully with a dominant icon — useful for hero/splash placements.",
 "The raised text baseline is a subtle asymmetry; don't mix with the centered lockups in one UI.",8,None,None),
("lockups","lock-07","lockups","Accented Heart","three dots as a type accent","typographic","includes text",
 "A small triad of dots sits as an accent/tittle above the 'a' in 'Heart' — the three Julia dots become a type-level detail rather than a separate icon.",
 "The most minimal/sophisticated option — no icon 'box', just a knowing detail for people who look twice.",
 "The accent is subtle; at very small sizes it can read as noise on the glyph — medium-to-large use only.",9,None,None),
("lockups","lock-10","lockups","Compact Fused Mark","beat-event dots (short timeline)","typographic","includes text",
 "Three small unequal-spaced beat-dots tucked under-left on a short baseline, sitting close to and almost fusing with the wordmark — the tightest horizontal lockup.",
 "The smallest footprint of the horizontal set — best for tight UI chrome (navbars, README badges).",
 "The dots are small (r≈15–17); keep a minimum render width (~200px) to preserve the Julia-dot identity.",10,None,None),
# -------- Comb × wordmark combos --------
("combos","combo-01","combos","Comb Underline","tick comb as underline","typographic","includes text",
 "The plain rule under the wordmark is replaced by the actual IBI comb — irregular ticks on a baseline, three dot-capped — so the underline itself is the beat raster.",
 "The closest 1:1 reuse of Base A's own vocabulary; instantly reads as 'comb become underline', very on-brief.",
 "The underline could be mistaken for decoration if scaled too small; keep dot caps visible.",1,None,None),
("combos","combo-08","combos","Cyclic Beat Arc","comb bent into an arc + dots","typographic","includes text",
 "The comb is bent into a shallow arc above the name (a cyclic beat); irregular ticks radiate off it and the three Julia dots sit on the arc at unequal angular spacing.",
 "The most distinctive silhouette of the combos — reads as a badge/seal from a distance while resolving into comb+dots up close.",
 "The arc must not be mistaken for a waveform; radiating ticks kept straight to avoid an ECG-adjacent read.",2,None,None),
("combos","combo-03","combos","Beat Timeline","beat-event dots on a timeline","typographic","includes text",
 "The three Julia dots sit on a timeline under the wordmark with clearly unequal gaps (plus a few minor ticks) — the timeline is the hero, the dots are beat events in time.",
 "The most literal expression of 'IBI' — the variable gap is the message; a very clean, calm composition.",
 "Can read as 'just 3 dots on a line' without the minor ticks; keep some comb texture.",3,None,None),
("combos","combo-04","combos","Interval Ruler","interval brackets / calipers","typographic","includes text",
 "A thin ruler runs under the single wordmark with three colored caliper marks at the syllable boundaries (Heart|Rate|Lab) — measuring the word itself like a sequence of intervals.",
 "Turns the wordmark into the 'signal being measured' — a clever literal fusion of typography and IBI measurement.",
 "Subtler than a literal comb; benefits from context on first exposure (docs/README).",4,None,None),
("combos","combo-06","combos","Stacked Comb + Name","IBI tick-comb (stacked)","typographic","includes text",
 "A compact vertical lockup — the IBI comb icon (near-verbatim Base A, scaled) above, the wordmark centered below.",
 "The most traditional 'icon + name' structure — a compact app-icon-adjacent lockup for square avatars.",
 "The least 'invented' fusion — more juxtaposition than fusion (kept per the brief's stacked requirement).",5,None,None),
("combos","combo-09","combos","Stacked Tachogram","tachogram (bars)","typographic","includes text",
 "A tachogram (bar heights = interval durations, three colored by the triad) sits above the wordmark in a compact vertical lockup.",
 "Introduces a second IBI vocabulary (bars, not ticks) into the stacked format — real variety versus combo-06.",
 "Bars can look like a generic analytics chart if muted; keep the three triad bars saturated.",6,None,None),
("combos","combo-07","combos","Diacritic Triad","dots as letter accents + comb","typographic","includes text",
 "The three Julia dots perch above the H, R and L like diacritics on the wordmark's ascenders; a plain grey comb runs beneath the word as the 'beat floor'.",
 "The most typographic fusion — the triad becomes part of the letterforms while the comb carries IBI honesty.",
 "Dot alignment over H/R/L is font-metric-approximate; verify at final render.",7,None,None),
("combos","combo-02","combos","Ticks Rising Into the Triad","event raster, dots as terminals","typographic","includes text",
 "A sparse row of minor grey ticks sits above the name; three grow tall and terminate in the Julia dots, so the triad reads as the comb's peaks floating over the wordmark.",
 "Inverts combo-01's placement (comb above, not below), giving variety while reusing the honest ticks+dots language.",
 "At small sizes the thin grey ticks may disappear, leaving three isolated dots.",8,None,None),
("combos","combo-05","combos","Three Syllable Combs","distributed tick comb","typographic","includes text",
 "Three small mini-combs (each with a dot-capped tall tick) sit under Heart·Rate·Lab on one shared baseline — the comb distributed under the word rather than concentrated.",
 "Ties each Julia-color dot to a syllable, reinforcing 'Heart-Rate-Lab' as three linked ideas under one timeline.",
 "Per-glyph alignment depends on font metrics; ticks may drift slightly off-syllable on other engines.",9,None,None),
("combos","combo-10","combos","Tachogram Baseplate","tachogram (bars)","typographic","includes text",
 "The tachogram bars run directly under the full-width wordmark like a textured baseplate/EQ meter — one continuous horizontal mark.",
 "Completes the set's coverage of all allowed IBI motifs in horizontal form; reads well small since bars are chunky.",
 "At very small sizes the thin bars blur together; reduce bar count for a favicon variant.",10,None,None),
]

def main():
    out=[]
    for g,id_,sub,title,motif,reg,wm,concept,why,risk,rank,top3,tr in D:
        e={"id":id_,"group":g,"file":f"{sub}/{id_}.svg","title":title,"motif":motif,
           "register":reg,"wordmark":wm,"concept":concept,"why":why,"risk":risk,"rank":rank}
        if top3: e["top3"]=top3; e["top3_reason"]=tr
        out.append(e)
    (HERE/"manifest2.json").write_text(json.dumps(out,indent=2,ensure_ascii=False))
    from collections import Counter
    print("manifest2.json:", dict(Counter(e['group'] for e in out)), "total", len(out),
          "| top3:", sorted([e['id'] for e in out if e.get('top3')]))

if __name__=="__main__":
    main()
